/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AuthStatus {
  'otpVerified' : boolean,
  'phone' : string,
  'registered' : boolean,
}
export interface Bet {
  'mode' : string,
  'target' : BetTarget,
  'roundId' : bigint,
  'amount' : number,
}
export type BetTarget = { 'color' : Color } |
  { 'number' : bigint };
export type Color = { 'red' : null } |
  { 'purple' : null } |
  { 'green' : null };
export interface GameState {
  'lastResults' : Array<RoundResult>,
  'currentRound' : Round,
}
export interface Round {
  'status' : RoundStatus,
  'winningNumber' : [] | [bigint],
  'winningColor' : [] | [Color],
  'mode' : string,
  'roundId' : bigint,
  'startTimestamp' : Time,
}
export interface RoundResult {
  'winningNumber' : bigint,
  'winningColor' : Color,
  'mode' : string,
  'roundId' : bigint,
  'timestamp' : Time,
}
export type RoundStatus = { 'settled' : null } |
  { 'open' : null } |
  { 'locked' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'phone' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deposit' : ActorMethod<[number], undefined>,
  'getAuthStatus' : ActorMethod<[], AuthStatus>,
  'getBalance' : ActorMethod<[], number>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameState' : ActorMethod<[string], GameState>,
  'getUserBets' : ActorMethod<[string, bigint], Array<Bet>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'lockRound' : ActorMethod<[string], undefined>,
  'placeBet' : ActorMethod<[string, BetTarget, number], undefined>,
  'requestOtp' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPassword' : ActorMethod<[string], boolean>,
  'settleRound' : ActorMethod<[string], RoundResult>,
  'verifyOtp' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];