/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AuthStatus = IDL.Record({
  'otpVerified' : IDL.Bool,
  'phone' : IDL.Text,
  'registered' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'phone' : IDL.Text,
});
export const Color = IDL.Variant({
  'red' : IDL.Null,
  'purple' : IDL.Null,
  'green' : IDL.Null,
});
export const Time = IDL.Int;
export const RoundResult = IDL.Record({
  'winningNumber' : IDL.Nat,
  'winningColor' : Color,
  'mode' : IDL.Text,
  'roundId' : IDL.Nat,
  'timestamp' : Time,
});
export const RoundStatus = IDL.Variant({
  'settled' : IDL.Null,
  'open' : IDL.Null,
  'locked' : IDL.Null,
});
export const Round = IDL.Record({
  'status' : RoundStatus,
  'winningNumber' : IDL.Opt(IDL.Nat),
  'winningColor' : IDL.Opt(Color),
  'mode' : IDL.Text,
  'roundId' : IDL.Nat,
  'startTimestamp' : Time,
});
export const GameState = IDL.Record({
  'lastResults' : IDL.Vec(RoundResult),
  'currentRound' : Round,
});
export const BetTarget = IDL.Variant({ 'color' : Color, 'number' : IDL.Nat });
export const Bet = IDL.Record({
  'mode' : IDL.Text,
  'target' : BetTarget,
  'roundId' : IDL.Nat,
  'amount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deposit' : IDL.Func([IDL.Float64], [], []),
  'getAuthStatus' : IDL.Func([], [AuthStatus], ['query']),
  'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameState' : IDL.Func([IDL.Text], [GameState], ['query']),
  'getUserBets' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Bet)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'lockRound' : IDL.Func([IDL.Text], [], []),
  'placeBet' : IDL.Func([IDL.Text, BetTarget, IDL.Float64], [], []),
  'requestOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'settleRound' : IDL.Func([IDL.Text], [RoundResult], []),
  'verifyOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AuthStatus = IDL.Record({
    'otpVerified' : IDL.Bool,
    'phone' : IDL.Text,
    'registered' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'phone' : IDL.Text });
  const Color = IDL.Variant({
    'red' : IDL.Null,
    'purple' : IDL.Null,
    'green' : IDL.Null,
  });
  const Time = IDL.Int;
  const RoundResult = IDL.Record({
    'winningNumber' : IDL.Nat,
    'winningColor' : Color,
    'mode' : IDL.Text,
    'roundId' : IDL.Nat,
    'timestamp' : Time,
  });
  const RoundStatus = IDL.Variant({
    'settled' : IDL.Null,
    'open' : IDL.Null,
    'locked' : IDL.Null,
  });
  const Round = IDL.Record({
    'status' : RoundStatus,
    'winningNumber' : IDL.Opt(IDL.Nat),
    'winningColor' : IDL.Opt(Color),
    'mode' : IDL.Text,
    'roundId' : IDL.Nat,
    'startTimestamp' : Time,
  });
  const GameState = IDL.Record({
    'lastResults' : IDL.Vec(RoundResult),
    'currentRound' : Round,
  });
  const BetTarget = IDL.Variant({ 'color' : Color, 'number' : IDL.Nat });
  const Bet = IDL.Record({
    'mode' : IDL.Text,
    'target' : BetTarget,
    'roundId' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deposit' : IDL.Func([IDL.Float64], [], []),
    'getAuthStatus' : IDL.Func([], [AuthStatus], ['query']),
    'getBalance' : IDL.Func([], [IDL.Float64], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameState' : IDL.Func([IDL.Text], [GameState], ['query']),
    'getUserBets' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Vec(Bet)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'lockRound' : IDL.Func([IDL.Text], [], []),
    'placeBet' : IDL.Func([IDL.Text, BetTarget, IDL.Float64], [], []),
    'requestOtp' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'settleRound' : IDL.Func([IDL.Text], [RoundResult], []),
    'verifyOtp' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };